#
---
name: Deploy To live.Iamdomchap90.net

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: Iamdomchap90/github-actions/.github/workflows/deploy-live-two.yml@main
    secrets: inherit

#
