#
---
name: Deploy To dev.Iamdomchap90.net

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    uses: Iamdomchap90/github-actions/.github/workflows/deploy-dev.yml@main
    secrets: inherit

#
